"""create jobs, job_analysis, applications tables

Revision ID: 96c08e9368ab
Revises: 
Create Date: 2026-09-16 12:10:00.579981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96c08e9368ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cv_path', sa.String(length=1024), nullable=False),
    sa.Column('gmail_draft_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.create_table('job_analysis',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('seniority', sa.String(length=32), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('frameworks', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('cloud', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ai_related', sa.Boolean(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('recommended_cv', sa.String(length=255), nullable=True),
    sa.Column('generated_email', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_analysis')
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
