"""add unique constraint on applications job_id

Revision ID: ff54eda02789
Revises: 96c08e9368ab
Create Date: 2026-09-17 18:08:26.551900

Refuerza a nivel de DB la invariante ya documentada en el Protocol
`ApplicationRepository.get_by_job_id` (`app/domain/repositories/
application_repository.py`) y asumida para idempotencia por
`CreateGmailDraft` en la capa de aplicación: el flujo actual genera a lo
sumo una `Application` por `Job`. Antes de este constraint, dos requests
casi simultáneas de creación de draft para el mismo job podían insertar dos
filas `applications` antes de que la primera hiciera commit, rompiendo esa
invariante y provocando `MultipleResultsFound` en `get_by_job_id()`.

Verificado antes de aplicar (ver reporte de `database-agent`): no existían
filas duplicadas de `job_id` en `applications` en la base de test/desarrollo
al momento de esta migración, por lo que `upgrade()` no requiere backfill ni
resolución manual de conflictos.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff54eda02789'
down_revision: Union[str, Sequence[str], None] = '96c08e9368ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_applications_job_id', 'applications', ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_applications_job_id', 'applications', type_='unique')
    # ### end Alembic commands ###
